version: '2'

services:
  sip:
    image: mcchae/sip-server
    container_name: sip_server
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "10000-10099:10000-10099/udp"
      - "8088:8088"
      - "8089:8089"
#     - "192.168.100.10:5060:5060/udp"
#     - "192.168.100.10:5060:5060/tcp"
#     - "192.168.100.10:10000-10099:10000-10099/udp"
#     - "192.168.100.10:8088:8088"
#     - "192.168.100.10:8089:8089"
    volumes:
      - "./var/conf/msmtprc:/etc/msmtprc"
      - "./var/conf/asterisk:/etc/asterisk"
      - "./var/data/asterisk:/var/lib/asterisk"
      - "./var/data/asterisk-spool:/var/spool/asterisk"
      - "./var/ssl:/ssl"
    # tcpdump -i any -nn udp
  siptest:
    image: ubuntu
    container_name: sip_client
    links:
      - sip
    command: /bin/sleep 1000
    # apt update && apt install -y iputils-ping ...
    # ...
